//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipl.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SipDatabaseEntities : DbContext
    {
        public SipDatabaseEntities()
            : base("name=SipDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<NetRoles> NetRoles { get; set; }
        public virtual DbSet<NetUsers> NetUsers { get; set; }
        public virtual DbSet<states> states { get; set; }
        public virtual DbSet<SubjectInCourse> SubjectInCourse { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TeacherInSubject> TeacherInSubject { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
