//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipl.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public byte UserId { get; set; }
        public string RoleId { get; set; }
        public int Id { get; set; }
    
        public virtual NetRoles NetRoles { get; set; }
        public virtual NetRoles NetRoles1 { get; set; }
        public virtual NetUsers NetUsers { get; set; }
    }
}
