//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiplDatabaseEntities19 : DbContext
    {
        public SiplDatabaseEntities19()
            : base("name=SiplDatabaseEntities19")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<NetRole> NetRoles { get; set; }
        public virtual DbSet<NetUser> NetUsers { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<SubjectInCourse> SubjectInCourses { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeacherInSubject> TeacherInSubjects { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
