//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public byte UserId { get; set; }
        public string RoleId { get; set; }
        public int Id { get; set; }
    
        public virtual NetRole NetRole { get; set; }
        public virtual NetUser NetUser { get; set; }
        public virtual NetUser NetUser1 { get; set; }
    }
}
